insert into course_db (name, coordinator_id) values ('Assistant Professor', 261),
 ('Junior Executive', 235),
 ('Technical Writer', 168),
 ('Engineer III', 580),
 ('Senior Cost Accountant', 327),
 ('Nurse Practicioner', 395),
 ('Sales Representative', 481),
 ('Biostatistician III', 760),
 ('Programmer Analyst II', 867),
 ('Marketing Manager', 183),
 ('Compensation Analyst', 388),
 ('Financial Analyst', 51),
 ('Software Engineer I', 951),
 ('Director of Sales', 336),
 ('Database Administrator II', 367),
 ('Engineer II', 689),
 ('Tax Accountant', 68),
 ('Web Developer IV', 527),
 ('Chief Design Engineer', 370),
 ('Clinical Specialist', 898),
 ('Senior Cost Accountant', 533),
 ('Teacher', 850),
 ('Assistant Media Planner', 736),
 ('Automation Specialist III', 532),
 ('Librarian', 188),
 ('Staff Scientist', 70),
 ('Electrical Engineer', 459),
 ('Senior Sales Associate', 59),
 ('Research Associate', 743),
 ('Geological Engineer', 186),
 ('Junior Executive', 153),
 ('Food Chemist', 653),
 ('Research Assistant III', 512),
 ('Tax Accountant', 805),
 ('Structural Analysis Engineer', 416),
 ('Quality Engineer', 709),
 ('Programmer I', 26),
 ('Physical Therapy Assistant', 242),
 ('Senior Quality Engineer', 921),
 ('Product Engineer', 66),
 ('Editor', 271),
 ('Programmer III', 595),
 ('Registered Nurse', 132),
 ('Office Assistant II', 562),
 ('Actuary', 332),
 ('Pharmacist', 801),
 ('Environmental Tech', 663),
 ('Senior Cost Accountant', 19),
 ('Environmental Tech', 955),
 ('Senior Editor', 307),
 ('Systems Administrator III', 619),
 ('Graphic Designer', 312),
 ('Environmental Tech', 566),
 ('Social Worker', 157),
 ('Assistant Media Planner', 480),
 ('Human Resources Assistant II', 322),
 ('Graphic Designer', 953),
 ('Design Engineer', 742),
 ('Chemical Engineer', 404),
 ('Clinical Specialist', 915),
 ('Chief Design Engineer', 479),
 ('Office Assistant I', 384),
 ('Assistant Manager', 237),
 ('Desktop Support Technician', 950),
 ('Tax Accountant', 511),
 ('Executive Secretary', 580),
 ('Pharmacist', 779),
 ('Web Developer II', 121),
 ('Senior Financial Analyst', 575),
 ('Director of Sales', 623),
 ('Help Desk Operator', 923),
 ('Media Manager I', 861),
 ('Electrical Engineer', 152),
 ('Administrative Officer', 76),
 ('Human Resources Assistant IV', 894),
 ('Senior Cost Accountant', 790),
 ('VP Sales', 196),
 ('Quality Engineer', 341),
 ('Cost Accountant', 133),
 ('Junior Executive', 66),
 ('Quality Engineer', 865),
 ('Associate Professor', 625),
 ('Civil Engineer', 449),
 ('Chief Design Engineer', 351),
 ('Financial Analyst', 807),
 ('Systems Administrator III', 823),
 ('Geological Engineer', 59),
 ('Assistant Manager', 591),
 ('Sales Representative', 771),
 ('Registered Nurse', 138),
 ('Analog Circuit Design manager', 825),
 ('Quality Engineer', 692),
 ('Director of Sales', 957),
 ('Design Engineer', 504),
 ('Programmer III', 120),
 ('Community Outreach Specialist', 766),
 ('Web Designer I', 687),
 ('GIS Technical Architect', 513),
 ('Media Manager III', 791),
 ('Research Assistant III', 846),
 ('Recruiting Manager', 157),
 ('Civil Engineer', 374),
 ('Budget/Accounting Analyst III', 263),
 ('Software Engineer IV', 444),
 ('Assistant Professor', 562),
 ('Software Test Engineer II', 472),
 ('Registered Nurse', 462),
 ('Nuclear Power Engineer', 634),
 ('Environmental Tech', 613),
 ('Nuclear Power Engineer', 694),
 ('Research Assistant I', 970),
 ('Cost Accountant', 430),
 ('Cost Accountant', 748),
 ('Assistant Professor', 140),
 ('Sales Associate', 601),
 ('Software Engineer IV', 900),
 ('Media Manager III', 63),
 ('Chief Design Engineer', 534),
 ('Software Engineer II', 973),
 ('Senior Quality Engineer', 456),
 ('Nurse Practicioner', 773),
 ('Programmer III', 966),
 ('Environmental Tech', 589),
 ('Registered Nurse', 574),
 ('Senior Sales Associate', 306),
 ('Cost Accountant', 810),
 ('Geologist I', 422),
 ('Programmer IV', 489),
 ('Geological Engineer', 926),
 ('Tax Accountant', 429),
 ('Cost Accountant', 671),
 ('VP Marketing', 748),
 ('Recruiting Manager', 717),
 ('Senior Financial Analyst', 342),
 ('Assistant Professor', 485),
 ('Pharmacist', 308),
 ('Nuclear Power Engineer', 44),
 ('Civil Engineer', 206),
 ('Staff Accountant IV', 852),
 ('Software Test Engineer I', 138),
 ('Staff Scientist', 940),
 ('Structural Analysis Engineer', 396),
 ('Marketing Manager', 960),
 ('Senior Quality Engineer', 733),
 ('Developer III', 151),
 ('Assistant Manager', 257),
 ('Technical Writer', 831),
 ('Geological Engineer', 652),
 ('Budget/Accounting Analyst IV', 989),
 ('Legal Assistant', 482),
 ('Actuary', 408),
 ('Professor', 703),
 ('Physical Therapy Assistant', 125),
 ('VP Sales', 603),
 ('Executive Secretary', 177),
 ('Financial Advisor', 869),
 ('Dental Hygienist', 801),
 ('Programmer Analyst I', 255),
 ('Database Administrator II', 767),
 ('Staff Accountant III', 704),
 ('Research Associate', 640),
 ('Geologist III', 692),
 ('Health Coach IV', 263),
 ('Help Desk Operator', 6),
 ('Electrical Engineer', 200),
 ('VP Product Management', 215),
 ('Civil Engineer', 771),
 ('Technical Writer', 251),
 ('Quality Control Specialist', 61),
 ('Staff Scientist', 643),
 ('Staff Accountant I', 867),
 ('Director of Sales', 123),
 ('Social Worker', 295),
 ('Chemical Engineer', 39),
 ('Pharmacist', 712),
 ('Nurse Practicioner', 151),
 ('Senior Sales Associate', 548),
 ('Senior Developer', 708),
 ('Programmer Analyst IV', 526),
 ('Office Assistant I', 457),
 ('Senior Sales Associate', 127),
 ('Staff Scientist', 756),
 ('Compensation Analyst', 611),
 ('Clinical Specialist', 780),
 ('Programmer I', 732),
 ('Human Resources Manager', 642),
 ('Media Manager I', 860),
 ('GIS Technical Architect', 811),
 ('Design Engineer', 384),
 ('Chemical Engineer', 236),
 ('Staff Accountant IV', 159),
 ('Human Resources Assistant I', 896),
 ('Staff Accountant I', 753),
 ('Financial Advisor', 560),
 ('Information Systems Manager', 438),
 ('Assistant Manager', 412),
 ('Help Desk Operator', 480),
 ('Nurse Practicioner', 355),
 ('Account Coordinator', 747),
 ('Geologist III', 717),
 ('Data Coordinator', 864),
 ('Administrative Officer', 821),
 ('Sales Representative', 615),
 ('Cost Accountant', 451),
 ('Software Engineer IV', 816),
 ('Web Developer III', 327),
 ('Librarian', 467),
 ('Marketing Manager', 928),
 ('Programmer Analyst III', 2),
 ('Operator', 396),
 ('Biostatistician II', 12),
 ('Sales Associate', 875),
 ('Chemical Engineer', 90),
 ('Dental Hygienist', 979),
 ('Computer Systems Analyst III', 837),
 ('Chief Design Engineer', 850),
 ('Dental Hygienist', 373),
 ('Nurse', 551),
 ('Senior Cost Accountant', 772),
 ('Assistant Media Planner', 86),
 ('Director of Sales', 482),
 ('Research Assistant I', 497),
 ('Recruiting Manager', 821),
 ('Help Desk Technician', 898),
 ('Automation Specialist II', 455),
 ('Junior Executive', 584),
 ('Marketing Manager', 567),
 ('Research Assistant I', 325),
 ('Business Systems Development Analyst', 258),
 ('Financial Advisor', 242),
 ('Technical Writer', 76),
 ('Actuary', 362),
 ('Physical Therapy Assistant', 184),
 ('Assistant Media Planner', 488),
 ('Administrative Assistant IV', 231),
 ('Help Desk Operator', 459),
 ('Electrical Engineer', 574),
 ('Help Desk Technician', 857),
 ('Operator', 10),
 ('Graphic Designer', 479),
 ('Biostatistician I', 693),
 ('Account Coordinator', 552),
 ('Marketing Manager', 869),
 ('Paralegal', 697),
 ('Actuary', 619),
 ('Programmer I', 648),
 ('Associate Professor', 455),
 ('Graphic Designer', 756),
 ('Information Systems Manager', 716),
 ('Marketing Assistant', 632),
 ('VP Marketing', 420),
 ('Senior Editor', 804),
 ('Compensation Analyst', 101),
 ('Structural Engineer', 410),
 ('Senior Sales Associate', 223),
 ('Environmental Specialist', 781),
 ('Structural Analysis Engineer', 474),
 ('Librarian', 574),
 ('Research Associate', 154),
 ('Developer I', 372),
 ('VP Quality Control', 555),
 ('Editor', 338),
 ('Research Assistant III', 320),
 ('Senior Editor', 672),
 ('Environmental Specialist', 909),
 ('Assistant Manager', 15),
 ('Biostatistician IV', 396),
 ('Tax Accountant', 1000),
 ('Electrical Engineer', 443),
 ('Research Assistant IV', 544),
 ('Actuary', 540),
 ('Senior Cost Accountant', 417),
 ('Nurse Practicioner', 982),
 ('Compensation Analyst', 485),
 ('Accounting Assistant II', 679),
 ('Desktop Support Technician', 716),
 ('Nuclear Power Engineer', 451),
 ('Pharmacist', 557),
 ('Executive Secretary', 637),
 ('Compensation Analyst', 400),
 ('Clinical Specialist', 223),
 ('Professor', 684),
 ('Geologist IV', 821),
 ('VP Sales', 765),
 ('Environmental Specialist', 647),
 ('VP Accounting', 177),
 ('Actuary', 535),
 ('Desktop Support Technician', 80),
 ('Junior Executive', 427),
 ('Community Outreach Specialist', 856),
 ('Technical Writer', 152),
 ('Staff Scientist', 119),
 ('Social Worker', 691),
 ('Sales Representative', 660),
 ('Legal Assistant', 546),
 ('Budget/Accounting Analyst I', 125),
 ('Actuary', 244),
 ('VP Quality Control', 91),
 ('Senior Cost Accountant', 288),
 ('Database Administrator II', 917),
 ('Senior Quality Engineer', 233),
 ('Librarian', 388),
 ('Automation Specialist II', 148),
 ('Pharmacist', 485),
 ('Assistant Media Planner', 364),
 ('VP Product Management', 534),
 ('Nurse', 304),
 ('Engineer I', 946),
 ('Nuclear Power Engineer', 795),
 ('Project Manager', 50),
 ('Staff Scientist', 435),
 ('Nurse Practicioner', 807),
 ('Account Representative III', 924),
 ('Quality Control Specialist', 694),
 ('Director of Sales', 860),
 ('Dental Hygienist', 544),
 ('Analyst Programmer', 772),
 ('Human Resources Manager', 144),
 ('Geological Engineer', 110),
 ('Senior Developer', 671),
 ('Geological Engineer', 816),
 ('Research Nurse', 673),
 ('Office Assistant III', 697),
 ('Programmer III', 919),
 ('Programmer II', 108),
 ('Legal Assistant', 999),
 ('Nuclear Power Engineer', 521),
 ('Programmer II', 253),
 ('Programmer Analyst IV', 580),
 ('Junior Executive', 778),
 ('Payment Adjustment Coordinator', 352),
 ('Information Systems Manager', 443),
 ('Research Nurse', 275),
 ('Cost Accountant', 15),
 ('Budget/Accounting Analyst I', 527),
 ('Marketing Manager', 715),
 ('Payment Adjustment Coordinator', 397),
 ('Health Coach IV', 277),
 ('Senior Sales Associate', 686),
 ('Tax Accountant', 113),
 ('Software Test Engineer I', 293),
 ('Help Desk Operator', 880),
 ('Geological Engineer', 788),
 ('Analog Circuit Design manager', 760),
 ('Senior Financial Analyst', 35),
 ('Environmental Tech', 65),
 ('Human Resources Assistant II', 793),
 ('Research Associate', 679),
 ('Sales Representative', 700),
 ('Software Engineer II', 913),
 ('Associate Professor', 15),
 ('Paralegal', 987),
 ('Design Engineer', 614),
 ('Media Manager I', 223),
 ('Environmental Specialist', 345),
 ('Nuclear Power Engineer', 129),
 ('Assistant Media Planner', 83),
 ('Human Resources Assistant II', 440),
 ('Dental Hygienist', 277),
 ('Assistant Professor', 781),
 ('Desktop Support Technician', 991),
 ('Librarian', 299),
 ('Help Desk Operator', 568),
 ('Desktop Support Technician', 993),
 ('Quality Control Specialist', 984),
 ('Senior Developer', 493),
 ('Registered Nurse', 497),
 ('Web Developer I', 690),
 ('Sales Associate', 294),
 ('Assistant Media Planner', 995),
 ('Geologist IV', 853),
 ('Assistant Professor', 215),
 ('Geological Engineer', 828),
 ('Quality Control Specialist', 490),
 ('Accounting Assistant III', 471),
 ('Recruiting Manager', 1),
 ('Software Consultant', 217),
 ('Chemical Engineer', 991),
 ('Recruiter', 804),
 ('Accountant II', 886),
 ('Sales Associate', 470),
 ('Software Consultant', 625),
 ('Sales Associate', 785),
 ('Pharmacist', 631),
 ('VP Quality Control', 341),
 ('Associate Professor', 707),
 ('Environmental Specialist', 11),
 ('Help Desk Operator', 76),
 ('Financial Advisor', 194),
 ('Office Assistant I', 853),
 ('Assistant Media Planner', 61),
 ('VP Sales', 561),
 ('Information Systems Manager', 786),
 ('Geological Engineer', 337),
 ('Project Manager', 156),
 ('Research Assistant III', 771),
 ('Director of Sales', 386),
 ('Accountant I', 63),
 ('Marketing Assistant', 81),
 ('Structural Analysis Engineer', 279),
 ('Office Assistant II', 249),
 ('Project Manager', 424),
 ('Graphic Designer', 586),
 ('Nuclear Power Engineer', 948),
 ('VP Product Management', 401),
 ('General Manager', 993),
 ('Desktop Support Technician', 436),
 ('Legal Assistant', 941),
 ('Executive Secretary', 746),
 ('Data Coordinator', 68),
 ('Programmer Analyst III', 811),
 ('Clinical Specialist', 967),
 ('Associate Professor', 843),
 ('Electrical Engineer', 661),
 ('Developer II', 381),
 ('Database Administrator II', 716),
 ('Civil Engineer', 804),
 ('Executive Secretary', 154),
 ('Structural Analysis Engineer', 402),
 ('Assistant Media Planner', 182),
 ('Safety Technician I', 996),
 ('Librarian', 743),
 ('Media Manager IV', 46),
 ('General Manager', 800),
 ('Research Assistant II', 793),
 ('Occupational Therapist', 545),
 ('Actuary', 382),
 ('Project Manager', 819),
 ('Occupational Therapist', 365),
 ('Research Nurse', 201),
 ('Food Chemist', 437),
 ('Speech Pathologist', 287),
 ('Software Engineer II', 905),
 ('Data Coordinator', 172),
 ('Quality Engineer', 437),
 ('Help Desk Technician', 992),
 ('Media Manager IV', 888),
 ('Occupational Therapist', 274),
 ('Staff Scientist', 111),
 ('Nurse Practicioner', 938),
 ('Web Designer I', 919),
 ('Assistant Professor', 231),
 ('Registered Nurse', 565),
 ('Account Coordinator', 354),
 ('Mechanical Systems Engineer', 492),
 ('Software Engineer III', 865),
 ('Accounting Assistant I', 879),
 ('Speech Pathologist', 777),
 ('Analyst Programmer', 446),
 ('Research Assistant IV', 161),
 ('Account Executive', 512),
 ('Research Nurse', 734),
 ('Media Manager I', 84),
 ('Programmer I', 989),
 ('Research Nurse', 639),
 ('Operator', 973),
 ('Engineer IV', 958),
 ('Research Associate', 656),
 ('Office Assistant I', 268),
 ('Assistant Media Planner', 727),
 ('Librarian', 811),
 ('Associate Professor', 527),
 ('Software Engineer IV', 907),
 ('Senior Sales Associate', 918),
 ('Junior Executive', 308),
 ('VP Accounting', 766),
 ('Administrative Assistant I', 182),
 ('Paralegal', 615),
 ('Structural Engineer', 913),
 ('Director of Sales', 309),
 ('Information Systems Manager', 34),
 ('Sales Associate', 356),
 ('Office Assistant IV', 460),
 ('Graphic Designer', 784),
 ('Desktop Support Technician', 514),
 ('Geological Engineer', 807),
 ('Analyst Programmer', 125),
 ('Business Systems Development Analyst', 625),
 ('Assistant Professor', 630),
 ('Accounting Assistant III', 277),
 ('Mechanical Systems Engineer', 31),
 ('Programmer IV', 506),
 ('Programmer Analyst II', 148),
 ('VP Sales', 253),
 ('Occupational Therapist', 7),
 ('Project Manager', 471),
 ('VP Marketing', 479),
 ('Occupational Therapist', 100),
 ('Technical Writer', 571),
 ('VP Sales', 6),
 ('Biostatistician IV', 238),
 ('Information Systems Manager', 76),
 ('Civil Engineer', 219),
 ('Nurse Practicioner', 849),
 ('Statistician IV', 545),
 ('Actuary', 520),
 ('Occupational Therapist', 438),
 ('VP Marketing', 607),
 ('Health Coach II', 412),
 ('Account Representative II', 235),
 ('Registered Nurse', 866),
 ('Information Systems Manager', 200),
 ('Teacher', 97),
 ('Data Coordinator', 925),
 ('Senior Cost Accountant', 748),
 ('Librarian', 453),
 ('Recruiter', 684),
 ('Quality Control Specialist', 547),
 ('Nurse Practicioner', 859),
 ('Statistician IV', 478),
 ('Desktop Support Technician', 893),
 ('Assistant Media Planner', 541),
 ('Project Manager', 853),
 ('Systems Administrator III', 243),
 ('Environmental Specialist', 304),
 ('Human Resources Manager', 937),
 ('Mechanical Systems Engineer', 855),
 ('Payment Adjustment Coordinator', 739),
 ('Software Engineer I', 865),
 ('Safety Technician I', 305),
 ('Paralegal', 539),
 ('Financial Advisor', 368),
 ('Quality Engineer', 662),
 ('Developer I', 282),
 ('Financial Advisor', 957),
 ('Human Resources Manager', 805),
 ('Software Consultant', 189),
 ('VP Quality Control', 26),
 ('Electrical Engineer', 881),
 ('Technical Writer', 835),
 ('VP Product Management', 250),
 ('Cost Accountant', 160),
 ('Account Representative I', 172),
 ('Software Test Engineer II', 696),
 ('Speech Pathologist', 913),
 ('Geological Engineer', 455),
 ('Mechanical Systems Engineer', 866),
 ('Community Outreach Specialist', 248),
 ('Office Assistant IV', 485),
 ('Senior Financial Analyst', 961),
 ('VP Quality Control', 12),
 ('Biostatistician I', 133),
 ('Social Worker', 571),
 ('Tax Accountant', 673),
 ('VP Accounting', 550),
 ('Help Desk Operator', 667),
 ('Media Manager III', 828),
 ('Statistician I', 987),
 ('Engineer II', 692),
 ('Research Nurse', 724),
 ('Software Test Engineer IV', 528),
 ('Research Nurse', 797),
 ('Administrative Assistant III', 116),
 ('Senior Cost Accountant', 867),
 ('Data Coordinator', 940),
 ('Electrical Engineer', 393),
 ('Information Systems Manager', 797),
 ('Data Coordinator', 402),
 ('Safety Technician II', 974),
 ('Recruiter', 468),
 ('Associate Professor', 656),
 ('Environmental Tech', 649),
 ('Senior Developer', 417),
 ('Associate Professor', 878),
 ('Media Manager II', 103),
 ('Staff Accountant IV', 820),
 ('Teacher', 548),
 ('Senior Developer', 914),
 ('Compensation Analyst', 5),
 ('Programmer III', 63),
 ('VP Sales', 580),
 ('Physical Therapy Assistant', 817),
 ('Community Outreach Specialist', 380),
 ('Civil Engineer', 261),
 ('VP Accounting', 632),
 ('Project Manager', 5),
 ('Senior Editor', 609),
 ('Project Manager', 802),
 ('Senior Developer', 465),
 ('Safety Technician IV', 253),
 ('Computer Systems Analyst I', 510),
 ('Computer Systems Analyst IV', 237),
 ('Nurse', 540),
 ('Software Test Engineer II', 83),
 ('Accounting Assistant IV', 223),
 ('Paralegal', 239),
 ('Research Nurse', 566),
 ('Product Engineer', 156),
 ('Librarian', 796),
 ('Statistician IV', 276),
 ('Structural Analysis Engineer', 23),
 ('Sales Representative', 760),
 ('Recruiter', 740),
 ('Help Desk Operator', 476),
 ('Executive Secretary', 229),
 ('Recruiting Manager', 343),
 ('Engineer I', 71),
 ('Teacher', 265),
 ('Sales Associate', 997),
 ('Senior Financial Analyst', 608),
 ('Safety Technician IV', 345),
 ('Administrative Assistant IV', 487),
 ('Administrative Officer', 843),
 ('Programmer IV', 437),
 ('Financial Analyst', 606),
 ('Nuclear Power Engineer', 222),
 ('Computer Systems Analyst I', 426),
 ('Health Coach IV', 933),
 ('Help Desk Operator', 60),
 ('Registered Nurse', 881),
 ('Speech Pathologist', 667),
 ('Occupational Therapist', 277),
 ('Software Consultant', 188),
 ('Recruiting Manager', 918),
 ('GIS Technical Architect', 93),
 ('Accountant I', 209),
 ('Accounting Assistant I', 760),
 ('Graphic Designer', 720),
 ('Research Nurse', 647),
 ('Civil Engineer', 857),
 ('Marketing Assistant', 147),
 ('Biostatistician IV', 126),
 ('VP Quality Control', 65),
 ('Actuary', 985),
 ('Nuclear Power Engineer', 409),
 ('Cost Accountant', 67),
 ('Help Desk Technician', 655),
 ('Senior Editor', 517),
 ('Senior Cost Accountant', 173),
 ('Quality Engineer', 178),
 ('Sales Associate', 543),
 ('Graphic Designer', 796),
 ('Engineer III', 283),
 ('General Manager', 998),
 ('Community Outreach Specialist', 566),
 ('Business Systems Development Analyst', 953),
 ('Systems Administrator IV', 141),
 ('Software Test Engineer I', 191),
 ('Internal Auditor', 355),
 ('General Manager', 355),
 ('Tax Accountant', 442),
 ('Data Coordinator', 211),
 ('Executive Secretary', 594),
 ('Chief Design Engineer', 773),
 ('Internal Auditor', 203),
 ('Senior Developer', 102),
 ('Graphic Designer', 62),
 ('Accounting Assistant III', 771),
 ('Engineer IV', 129),
 ('Account Representative IV', 383),
 ('Marketing Manager', 440),
 ('Senior Editor', 83),
 ('Assistant Manager', 987),
 ('Help Desk Technician', 169),
 ('Sales Representative', 596),
 ('Mechanical Systems Engineer', 762),
 ('Pharmacist', 350),
 ('Environmental Specialist', 479),
 ('Programmer Analyst II', 615),
 ('Database Administrator III', 751),
 ('Graphic Designer', 758),
 ('Nuclear Power Engineer', 220),
 ('Speech Pathologist', 301),
 ('Software Test Engineer II', 406),
 ('Environmental Tech', 519),
 ('Account Representative III', 524),
 ('Electrical Engineer', 850),
 ('General Manager', 527),
 ('Senior Cost Accountant', 894),
 ('Marketing Manager', 789),
 ('Speech Pathologist', 423),
 ('Recruiter', 581),
 ('Civil Engineer', 110),
 ('Quality Control Specialist', 842),
 ('Junior Executive', 124),
 ('Software Test Engineer II', 164),
 ('Analyst Programmer', 563),
 ('Account Executive', 699),
 ('Research Associate', 411),
 ('Account Representative IV', 71),
 ('Database Administrator II', 855),
 ('Administrative Assistant II', 174),
 ('Administrative Officer', 3),
 ('Actuary', 985),
 ('Senior Cost Accountant', 777),
 ('Electrical Engineer', 938),
 ('Help Desk Technician', 454),
 ('Internal Auditor', 508),
 ('Research Nurse', 690),
 ('Internal Auditor', 4),
 ('Technical Writer', 166),
 ('Technical Writer', 999),
 ('Senior Quality Engineer', 746),
 ('Statistician I', 858),
 ('Nurse', 169),
 ('Information Systems Manager', 294),
 ('Structural Engineer', 985),
 ('Senior Developer', 506),
 ('Software Consultant', 190),
 ('Staff Accountant II', 438),
 ('Marketing Assistant', 777),
 ('Occupational Therapist', 511),
 ('Nurse Practicioner', 244),
 ('Software Test Engineer II', 145),
 ('Software Consultant', 375),
 ('Chief Design Engineer', 491),
 ('Staff Scientist', 343),
 ('Administrative Officer', 35),
 ('Software Engineer IV', 124),
 ('Design Engineer', 396),
 ('Developer I', 226),
 ('Developer I', 797),
 ('Recruiter', 279),
 ('Software Test Engineer II', 923),
 ('Human Resources Manager', 529),
 ('Product Engineer', 327),
 ('Structural Analysis Engineer', 424),
 ('Web Designer III', 277),
 ('VP Sales', 375),
 ('Design Engineer', 108),
 ('Registered Nurse', 351),
 ('Compensation Analyst', 313),
 ('Director of Sales', 580),
 ('Assistant Media Planner', 474),
 ('Media Manager I', 211),
 ('Operator', 583),
 ('VP Sales', 383),
 ('VP Quality Control', 816),
 ('VP Quality Control', 475),
 ('VP Product Management', 313),
 ('Business Systems Development Analyst', 434),
 ('General Manager', 633),
 ('Web Designer III', 940),
 ('Structural Engineer', 501),
 ('Systems Administrator IV', 466),
 ('Systems Administrator I', 745),
 ('Tax Accountant', 690),
 ('Staff Scientist', 713),
 ('Chemical Engineer', 784),
 ('Physical Therapy Assistant', 463),
 ('Editor', 978),
 ('Professor', 983),
 ('Senior Developer', 733),
 ('Chemical Engineer', 145),
 ('Geological Engineer', 896),
 ('Software Engineer IV', 335),
 ('Dental Hygienist', 310),
 ('Editor', 37),
 ('Web Developer II', 610),
 ('Statistician IV', 904),
 ('Web Developer III', 553),
 ('Environmental Tech', 568),
 ('Software Consultant', 522),
 ('Editor', 335),
 ('Account Coordinator', 806),
 ('Design Engineer', 908),
 ('Quality Control Specialist', 842),
 ('Marketing Assistant', 440),
 ('Graphic Designer', 539),
 ('VP Quality Control', 127),
 ('Civil Engineer', 933),
 ('Business Systems Development Analyst', 142),
 ('Occupational Therapist', 107),
 ('Recruiting Manager', 337),
 ('Data Coordinator', 330),
 ('Analyst Programmer', 358),
 ('Assistant Manager', 997),
 ('Nuclear Power Engineer', 656),
 ('Marketing Assistant', 491),
 ('Mechanical Systems Engineer', 846),
 ('Chief Design Engineer', 225),
 ('Programmer Analyst III', 991),
 ('Research Assistant III', 702),
 ('Financial Advisor', 826),
 ('Professor', 49),
 ('Sales Representative', 268),
 ('Help Desk Technician', 149),
 ('Environmental Tech', 585),
 ('GIS Technical Architect', 834),
 ('Nuclear Power Engineer', 177),
 ('Automation Specialist III', 107),
 ('Accountant II', 361),
 ('Technical Writer', 613),
 ('General Manager', 706),
 ('Budget/Accounting Analyst III', 926),
 ('Internal Auditor', 19),
 ('Account Executive', 810),
 ('Clinical Specialist', 542),
 ('Tax Accountant', 979),
 ('Occupational Therapist', 401),
 ('VP Accounting', 534),
 ('VP Sales', 425),
 ('Tax Accountant', 658),
 ('Junior Executive', 925),
 ('Pharmacist', 491),
 ('Statistician IV', 372),
 ('Clinical Specialist', 967),
 ('Developer II', 438),
 ('Compensation Analyst', 257),
 ('Sales Associate', 578),
 ('Nurse Practicioner', 347),
 ('Software Engineer I', 603),
 ('Financial Advisor', 272),
 ('Research Associate', 351),
 ('Pharmacist', 875),
 ('Human Resources Assistant IV', 117),
 ('Tax Accountant', 700),
 ('Help Desk Operator', 357),
 ('Registered Nurse', 447),
 ('General Manager', 203),
 ('Technical Writer', 321),
 ('Physical Therapy Assistant', 476),
 ('Executive Secretary', 18),
 ('Desktop Support Technician', 863),
 ('Analog Circuit Design manager', 283),
 ('Food Chemist', 778),
 ('Automation Specialist I', 710),
 ('Senior Cost Accountant', 666),
 ('Administrative Assistant IV', 847),
 ('Administrative Officer', 2),
 ('Nurse', 775),
 ('Sales Associate', 932),
 ('Senior Editor', 15),
 ('Desktop Support Technician', 148),
 ('Associate Professor', 975),
 ('Programmer Analyst III', 628),
 ('Help Desk Technician', 851),
 ('Environmental Specialist', 988),
 ('Nurse Practicioner', 59),
 ('Statistician III', 633),
 ('Recruiter', 860),
 ('Analog Circuit Design manager', 152),
 ('Analog Circuit Design manager', 177),
 ('Software Test Engineer II', 127),
 ('VP Sales', 24),
 ('Librarian', 763),
 ('General Manager', 35),
 ('Financial Advisor', 143),
 ('Web Designer III', 665),
 ('Chief Design Engineer', 448),
 ('Media Manager I', 894),
 ('Nurse', 194),
 ('Research Assistant IV', 44),
 ('Graphic Designer', 186),
 ('Engineer I', 422),
 ('Systems Administrator III', 135),
 ('Editor', 413),
 ('Legal Assistant', 285),
 ('Analog Circuit Design manager', 480),
 ('Assistant Manager', 5),
 ('Assistant Professor', 178),
 ('Nurse', 331),
 ('Marketing Manager', 691),
 ('Geological Engineer', 851),
 ('Librarian', 273),
 ('Analyst Programmer', 57),
 ('Director of Sales', 926),
 ('Quality Control Specialist', 986),
 ('Occupational Therapist', 858),
 ('Accountant IV', 379),
 ('Senior Editor', 827),
 ('Sales Representative', 637),
 ('Recruiting Manager', 230),
 ('Clinical Specialist', 738),
 ('Internal Auditor', 301),
 ('Compensation Analyst', 731),
 ('Financial Analyst', 931),
 ('VP Quality Control', 135),
 ('Biostatistician III', 417),
 ('Dental Hygienist', 336),
 ('Biostatistician I', 762),
 ('Office Assistant I', 860),
 ('Information Systems Manager', 732),
 ('Director of Sales', 506),
 ('Senior Quality Engineer', 220),
 ('Assistant Manager', 815),
 ('Mechanical Systems Engineer', 913),
 ('Internal Auditor', 373),
 ('VP Marketing', 762),
 ('Graphic Designer', 6),
 ('Assistant Manager', 630),
 ('Web Developer IV', 702),
 ('Compensation Analyst', 525),
 ('Data Coordinator', 801),
 ('Civil Engineer', 437),
 ('Analyst Programmer', 720),
 ('Statistician III', 775),
 ('Sales Associate', 551),
 ('Recruiter', 125),
 ('Marketing Manager', 435),
 ('Administrative Officer', 240),
 ('Human Resources Assistant I', 676),
 ('Health Coach II', 793),
 ('Chief Design Engineer', 664),
 ('Staff Accountant I', 787),
 ('Assistant Media Planner', 289),
 ('Database Administrator III', 393),
 ('Staff Scientist', 802),
 ('Librarian', 258),
 ('Research Nurse', 684),
 ('Senior Financial Analyst', 916),
 ('Mechanical Systems Engineer', 904),
 ('Web Designer I', 99),
 ('Dental Hygienist', 845),
 ('Help Desk Technician', 604),
 ('VP Product Management', 282),
 ('Product Engineer', 197),
 ('Social Worker', 1000),
 ('Account Coordinator', 946),
 ('VP Quality Control', 9),
 ('Software Engineer II', 971),
 ('Teacher', 303),
 ('Staff Scientist', 573),
 ('Software Test Engineer III', 433),
 ('Nuclear Power Engineer', 708),
 ('Chemical Engineer', 414),
 ('Business Systems Development Analyst', 78),
 ('Associate Professor', 914),
 ('Account Executive', 275),
 ('Analyst Programmer', 586),
 ('Health Coach IV', 957),
 ('Web Designer IV', 715),
 ('Assistant Professor', 212),
 ('Clinical Specialist', 602),
 ('Cost Accountant', 904),
 ('Nuclear Power Engineer', 60),
 ('Sales Representative', 79),
 ('Systems Administrator II', 490),
 ('Senior Sales Associate', 264),
 ('Sales Representative', 504),
 ('Technical Writer', 16),
 ('Automation Specialist II', 495),
 ('Statistician III', 617),
 ('Electrical Engineer', 217),
 ('Geologist IV', 873),
 ('Electrical Engineer', 65),
 ('Quality Engineer', 110),
 ('Pharmacist', 614),
 ('Business Systems Development Analyst', 653),
 ('Paralegal', 721),
 ('Senior Sales Associate', 82),
 ('Account Executive', 841),
 ('Technical Writer', 30),
 ('Structural Engineer', 808),
 ('Research Nurse', 855),
 ('Graphic Designer', 952),
 ('Financial Analyst', 957),
 ('Senior Editor', 566),
 ('Community Outreach Specialist', 846),
 ('Chemical Engineer', 709),
 ('GIS Technical Architect', 444),
 ('Community Outreach Specialist', 609),
 ('Junior Executive', 247),
 ('Structural Engineer', 111),
 ('Structural Analysis Engineer', 283),
 ('Payment Adjustment Coordinator', 887),
 ('Research Nurse', 109),
 ('Media Manager III', 137),
 ('Community Outreach Specialist', 101),
 ('VP Product Management', 555),
 ('Administrative Assistant III', 822),
 ('Community Outreach Specialist', 798),
 ('Marketing Assistant', 909),
 ('Senior Editor', 746),
 ('Research Assistant I', 705),
 ('Product Engineer', 427),
 ('General Manager', 54),
 ('GIS Technical Architect', 437),
 ('Recruiter', 41),
 ('Business Systems Development Analyst', 195),
 ('Community Outreach Specialist', 255),
 ('Senior Quality Engineer', 361),
 ('Environmental Tech', 992),
 ('Associate Professor', 583),
 ('Marketing Manager', 930),
 ('Software Consultant', 756),
 ('Account Representative I', 674),
 ('Analyst Programmer', 599),
 ('Dental Hygienist', 354),
 ('Structural Engineer', 459),
 ('Teacher', 148),
 ('Research Nurse', 195),
 ('Desktop Support Technician', 192),
 ('Dental Hygienist', 138),
 ('Analog Circuit Design manager', 542),
 ('Recruiting Manager', 266),
 ('Civil Engineer', 342),
 ('Cost Accountant', 123),
 ('Research Nurse', 833),
 ('Environmental Specialist', 14),
 ('Sales Associate', 136),
 ('Geological Engineer', 307),
 ('Financial Analyst', 885),
 ('Research Assistant I', 169),
 ('Marketing Manager', 22),
 ('Software Consultant', 893),
 ('Developer III', 82),
 ('Assistant Media Planner', 649),
 ('Developer III', 292),
 ('Software Engineer III', 929);